config/routes.rb
Rails.application.routes.draw do
  root to: "places#index"
  devise_for :users

  resources :places do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_hour, presence: true
  validates :capicity, presence: true
  validates :category, presence: true
  belongs_to :user
  has_many :reservations
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_by_category,
    against: [ :title, :description, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :hour_quantity, numericality: {only_integer: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum :role, { Explorador: 0, Propietario: 1 }, default: :explorer, suffix: true
  before_create :user_default

  has_many :places
  has_many :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  private

  def user_default
    self.role = :Explorador
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name cellphone identification_number address avatar_url country])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_place, only: %i[show edit update destroy]
  def index
    if params[:query].present?
      @places = Place.search_by_category(params[:query])
    else
      @places = Place.all
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to root_path, notice: "Se ha agregado correctamente"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end
  
  def edit; end

  def update
    if @place.update(place_params)
      redirect_to place_path, notice: "Actualización exitosa"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place.destroy
    redirect_to place_path, notice: "Eliminación exitosa", status: :see_other
  end

  private

  def place_params
    params.require(:place).permit(:title, :description, :address, :category, :price_per_hour, :capicity, photos: [])
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_place, only: %i[new create]
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.place_id = @place.id
    @reservation.user_id = current_user.id
    @reservation.total_price = @place.price_per_hour * @reservation.hour_quantity
    if @reservation.save
      redirect_to @reservation
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)
    if @reservation.save
      redirect_to reservation_path(@reservation)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    # place = @reservation.place
    @reservation.destroy
    if Reservation.all.empty?
      redirect_to reservations_path, status: 200,
      flash: { notice: "No tienes reservaciones en el momento" }
    else
      redirect_to reservations_path, status: :see_other
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :visit_hour, :hour_quantity)
  end

  def set_place
    @place = Place.find(params[:place_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JoinpApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <div>
      <%= render 'shared/flashes' %>

    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/edit.html.erb
<div class="container">

  <h1 class="mt-10 mb-6">Modifica tu epacio ofertado</h1>

  <%= simple_form_for(@place) do |f| %>
      <% @place.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
      <% end %>
    <div class="form-inputs">
      <%= f.input :title, label:"Título" %>
      <%= f.input :description, label:"Descripción" %>
      <%= f.input :address, label:"Dirección" %>
      <%= f.input :category, label:"Categoría" %>
      <%= f.input :price_per_hour, label:"Precio por hora", placeholder: "COP" %>
      <%= f.input :capicity, label:"Capacidad", placeholder:"Ingresa la capacidad màxima del lugar", class:"pt-5" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>
    <div class="form-actions">
      <%= f.submit "Actualizar", class: "btn btn-primary m-3" %>
      <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-link"%></a>
    </div>

  <% end %>
</div>

app/views/places/index.html.erb
<div class="container">
  <%# <div class="row gy-4">
    <h1 class="mt-10 mb-6">JoinPeople</h1>
    <h3 class="mb-3"> Encuentra el mejor espacio que se adapte a tus necesidades para tus encuentros y eventos </h5>
  </div> %>
  <%= render "shared/banner" %>

  <%= render "shared/cards" %>

</div>

app/views/places/new.html.erb
<div class="container">
  <% current_user.id %>
  <h1 class="mt-10 mb-6">Agrega un nuevo espacio</h1>

  <%= simple_form_for(@place) do |f| %>
    <% @place.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
    <div class="form-inputs">
      <%= f.input :title, label:"Título" %>
      <%= f.input :description, label:"Descripción" %>
      <%= f.input :address, label:"Dirección" %>
      <%= f.input :category, label:"Categoría" %>
      <%= f.input :price_per_hour, label:"Precio por hora", placeholder: "COP" %>
      <%= f.input :capicity, label:"Capacidad", placeholder:"Ingresa la capacidad màxima del lugar", class:"pt-5" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>
    <div class="form-actions">
      <%= f.submit "Guardar", class: "btn btn-primary m-3" %>
      <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-link"%></a>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="container">
  <h1 class="mt-10 mb-6">JoinPeople</h1>
  <h3><%= @place.title%> (<%=@place.category %>)</h3>
  <div>
    <p>Detalles: <%= @place.description %></p>
    <p>Dirección: <%= @place.address %></p>
    <p>Capacidad: <%= @place.capicity %> personas</p>
    <p> Precio por hora: <%= @place.price_per_hour %> COP</p>
    <%# <%= image_tag @place.photo if @place.photo.attached? %>
    <% @place.photos.each do |photo| %>
        <%if @place.photos.attached? %>
          <%= image_tag photo, width: 100, height: 100 %>
        <% end %>
    <% end %>
    <br>
  <div class="mb-5"><%= link_to "Reservar", new_place_reservation_path(@place), class:"btn btn-primary"%></div>
  </div>

  <div class="d-flex">
    <% if current_user.present? && (current_user.id == @place.user_id) %>
      <div class="d-flex-inline">
        <a><%= link_to "Editar espacio", edit_place_path(@place), class:"btn btn-secondary" %></a>
        <a><%= link_to "Eliminar espacio", place_path(@place), class:"btn btn-secondary", data: {turbo_method: :delete, turbo_confirm: "¿Estas seguro de eliminar?"} %></a>
        <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-outline-secondary"%></a>
      </div>
    <% else %>
      <div class="d-flex-inline">
        <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-link"%></a>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="container">
  <h1 class="mt-10 mb-6">Editar esta reserva:
  "<strong><%= @reservation.place.title %></strong>"</h1>

  <%= simple_form_for [@place, @reservation] do |f| %>
  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :visit_hour %>
    <%= f.input :hour_quantity, id: "hours" %>
  </div>
    <div class="form-actions">
      <%= f.submit "Confirmar Reserva", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>
  <div class="d-flex-inline">
    <a class="mb-5"><%= link_to "Regresar", reservation_path(@reservation), class:"btn btn-link"%></a>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <h1>Mis Reservas JoinPeople</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @reservations.each do |reservation| %>
    <div class="col">
        <div class="card h-100 " style="width: 18rem;">
          <div class="box card-body">
            <h4 class="card-title fw-bold" ><%= reservation.place.title %>  (<%= reservation.place.category %>)</h4>
            <% if reservation.place.photos.blank? %>
              <%= image_tag reservation.place.photo_url, width: 100, height: 100, class:"card-img-top" %>
            <% else %>
              <%= image_tag reservation.place.photos[0], width: 100, height: 100, class:"card-img-top" %>
            <% end %>
            <p class="card-title">Fecha: <%= reservation.date %></p>
            <p class="card-title">Hora de llegada: <%= reservation.visit_hour %></p>
            <p class="card-title">Cantidad de horas:<%= reservation.hour_quantity %></p>
            <p class="card-title">Precio total $: <%= reservation.total_price%></p>
            <div class="d-flex-inline">
              <a><%= link_to "Editar mi reserva", edit_reservation_path(reservation), class:"btn btn-secondary p-0" %></a>
              <%= link_to "Eliminar",
                reservation_path(reservation), method: :delete, class:"btn btn-secondary p-0",
                data: {turbo_method: :delete, turbo_confirm: "¿Deseas eliminar esta reservación?"}
              %>
            </div>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <div class="d-flex-inline">
    <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-link"%></a>
  </div>
</div>
<!--
<%# <%= reservation.place.title %> <%#= reservation.date %>
<img src="<%#= reservation.place.photo_url %>" width="200px" alt="">
-->

app/views/reservations/new.html.erb
<div class="container">
  <h1 class="mt-10 mb-6">Reservar este lugar:
  "<strong><%= @place.title %></strong>"</h1>
  
  <%= simple_form_for [@place, @reservation] do |f| %>
  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :visit_hour %>
    <%= f.input :hour_quantity, id: "hours" %>
  </div>
    <div class="form-actions">
      <%= f.submit "Confirmar Reserva", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>

  <%# <div class="mt-16">
    <h4 class="mt-4">Resumen de Pago</h4>
    <div class="mt-8">
      <h5><strong>Valor por hora:</strong></h5>
      <p id="price_hour"><%= @place.price_per_hour %>
      <%# <h5><strong>Total horas reservadas:</strong></h5>
      <p id="num_hour"><%= @reservation.hour_quantity %>
    <%# </div> %>

    <%# <div class=""
         data-controller="payment-value"
         data-action="click->payment-value#total-pay">
      <h5><strong>Total Reserva:</strong></h5>
      <p id="total"></p>
    </div> %>
    <%# <script>
      let price;
      price = document.querySelector('#price_hour').textContent;

      let hour;
      hour = document.querySelector('#num_hour').textContent;

      let submit_button = document.querySelector('.btn');
      console.log("price: ", price)
      console.log("hours: ", hour)
      submit_button.addEventListener('click', totalReservation());


      function totalReservation() {

        let payment = parseInt(price, 10) * parseInt(hour, 10);
        document.querySelector("#total").innerHTML.value = payment;
      }
      console.log("hours: ", hour)
    </script> %>
    <%#


    <%# <button class="btn btn-outline-primary mt-4" data-controller="payment-value" data-action="click->payment-value#total-pay">
      CALCULAR TOTAL
    </button> %>

    <%# <div class="total mt-5">
      <% let price = document.querySelector('') %>
      <%# <%= @reservation.hour_quantity * @place.price_per_hour %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <h1><%= @reservation.place.title %></h1>
  <div class="row gap-4">

      <%# <div class="col"> %>
    <div class="card" style="width: 36rem;">
    <%# h-100 col col-md-3 %>
      <%# @reservation.place.photos.each do |photo| %>
        <%#= image_tag photo, width: 100, height: 100, class:"card-img mt-3" %>
      <%# end %>
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @reservation.place.photos.each do |photo| %>
          <div class="carousel-item active">
            <%= image_tag photo, width: 150, height: 100, class:"d-block w-100 mt-3" %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="box card-body">
            <h4 class="card-title fw-bold" ><%= @reservation.place.category %></h4>
            <p class="card-title">Fecha: <%= @reservation.date %></p>
            <p class="card-title">Hora de llegada: <%= @reservation.visit_hour %></p>
            <p class="card-title">Cantidad de horas: <%= @reservation.hour_quantity %></p>
            <p class="card-title">Precio total $: <%= @reservation.total_price%></p>
            <%# <div class="d-flex-inline"> %>
              <%= link_to "Eliminar reserva",
                reservation_path(@reservation), method: :delete, class:"btn btn-secondary p-0 m-1",
                data: {turbo_method: :delete, turbo_confirm: "¿Deseas eliminar esta reservación?"}
              %>
              <%= link_to "Editar reserva",
                edit_reservation_path(@reservation), method: :update, class:"btn btn-secondary p-0 m-1",
                data: {turbo_method: :update, turbo_confirm: "¿Deseas actualizar esta reservación?"}
              %>
            <%# </div> %>
            <div class="d-flex-inline">
              <a class="mb-5"><%= link_to "Regresar", places_path, class:"btn btn-link"%></a>
            </div>
          </div>
        </div>
      <%# </div> %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="container">
  <%# <div class="banner-letters">
    <h1>JoinPeople</h1>
    <h3> Encuentra el mejor espacio que se adapte a tus necesidades para tus encuentros y eventos </h5>
    <div class="m-10 align-items-center">
      <%= render "shared/search" %>
    <!-- </div>
    <div class="banner" url(https://ibb.co/2PrCnNd);">
    </div>
  </div>
</div> -->

<div class="card bg-light text-black">
  <img src="https://i.ibb.co/vhv7S1L/s-o-c-i-a-l-c-u-t-ww8hlj-WABIE-unsplash.jpg" class="card-img"
   style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)); max-height: 20rem">
  <div class="card-img-overlay">
    <h1 class="card-title-dark">JoinPeople</h1>
    <h3 class="card-text">Encuentra el mejor espacio que se adapte a tus necesidades para tus encuentros y eventos</h3>
    <br>
    <br>
    <div class="d-flex">
      <div class="align-items-center"><%= render "shared/search" %></div>
    </div>
  </div>
</div>
<br>

app/views/shared/_cards.html.erb
<div class="container">
<div class="">
    <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @places.each do |place| %>
      <div class="col">
        <div class="card h-100 " style="width: 18rem;">
            <% if place.photos.blank? %>
              <%= image_tag place.photo_url, width: 100, height: 100, class:"card-img-top" %>
            <% else %>
              <%= image_tag place.photos[0], width: 100, height: 100, class:"card-img-top" %>
              <%# place.photos.each do |photo| %>
                <%#= image_tag photo, width: 100, height: 100, class:"card-img-top" %>
              <%# end %>
            <% end %>
            <div class="box card-body">
              <h5 class="card-title fw-bold" ><%= place.title %>  (<%= place.category %>)</h5>
              <p class="card-text"><%= place.description %></p>
              <%= link_to "Ver más", place_path(place.id), class:"btn btn-primary"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at JoinPeople
  </div>
</div> %>

<!-- Footer -->

<footer class="text-center text-lg-start bg-white text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Encuéntranos en nuestras redes sociales:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3 text-secondary"></i>JoinPeople
          </h6>
          <p>
            ¡ Bienvenido a JoinPeople !
            En nuestro sitio web podrás encontrar los mejores
            espacios de Medellín para cualquier necesidad que tengas: coworkings, parqueaderos,
            miradores y entre otra infinidad de opciones.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Espacios
          </h6>
          <p>
            <a href="/places" class="text-reset">Home</a>
          </p>
          <p>
            <a href="users/id" class="text-reset">Dashboard</a>
          </p>
          <p>
            <a href="users/edit" class="text-reset">Perfil</a>
          </p>
          <p>
            <a href="#!" class="text-reset"></a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">

          </h6>
          <p>
            <a href="/places" class="text-reset">Preguntas frecuentes</a>
          </p>
          <p>
            <a href="/places" class="text-reset">Quiénes somos</a>
          </p>
          <p>
            <a href="#!" class="text-reset"></a>
          </p>
          <p>
            <a href="/places" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contactos</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i> Antioquia, Medellín, CO</p>
          <p>
            <i class="fas fa-envelope me-3 text-secondary"></i>
            joinp@joinpeople.com
          </p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 57 234 567 88</p>
          <p><i class="fas fa-print me-3 text-secondary"></i> + 57 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_form.html.erb
<%= simple_form_for(@place) do |f| %>

  <div class="form-inputs">
    <%= f.input :title, label:"Título" %>
    <%= f.input :description, label:"Descripción" %>
    <%= f.input :address, label:"Dirección" %>
    <%= f.input :category, label:"Categoría" %>
    <%= f.input :price_per_hour, label:"Precio por hora", placeholder: "COP" %>
    <%= f.input :capicity, label:"Capacidad", placeholder:"Ingresa la capacidad màxima del lugar", class:"pt-5" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

  <!--<%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.errors[:base].present? %>
  -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/places">
      <img class="rounded-circle border border-1" src="https://i.ibb.co/kg0Q3sc/Whats-App-Image-2022-09-27-at-10-09-17-PM.jpg" />
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# current_user.role = "Explorador" %>
          <li class="nav-item">
            <a href="users/edit" class="nav-link"><%= current_user.first_name %> <%= current_user.last_name %></a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/places">Home</a>
          </li>
          <li class="nav-item">
            <div class="btn btn-info p-0 m-1"><strong><%= link_to "Ofrece tu espacio", new_place_path, class: "nav-link" %></strong></div>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://i.ibb.co/PhGQjV9/Whats-App-Image-2022-09-27-at-10-09-17-PM-1.jpg", class: "avatar dropdown-toggle rounded-circle border border-1", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Perfil", "users/edit", class: "dropdown-item" %>
              <%= link_to "Mis Reservaciones", reservations_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_photos.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% reservation.place.photos.each do |photo| %>
    <div class="carousel-item active">
      <%= image_tag photo, width: 100, height: 100, class:"d-block w-100" %>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="container-fluid">
  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <%= form_with url: places_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Encuentra un lugar"
        %>
    </div>
    <div class="col-auto">
      <%= submit_tag "Buscar", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>